[versions]
agp = "9.2.1"
junit = "4.13.2"
gson = "2.10.1"
androidxCore = "1.16.0"
robolectric = "4.16.1"
nexusSdk = "sdk-v0.15.0"

[libraries]
junit = { module = "junit:junit", version.ref = "junit" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
androidx-core = { module = "androidx.core:core", version.ref = "androidxCore" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
rokid-nexus-bus-client = { module = "com.github.Anezium.Rokid-Nexus:bus-client", version.ref = "nexusSdk" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
